const t={
 ar:{eyebrow:'قائمة الطعام والمشروبات',title:'WAVES Beach Lounge',subtitle:'منيو خفيف وسريع للفتح على كل الموبايلات.',search:'ابحث في المنيو...'},
 en:{eyebrow:'Food & Drinks Menu',title:'WAVES Beach Lounge',subtitle:'A lightweight menu built to open fast on all phones.',search:'Search the menu...'},
 ru:{eyebrow:'Меню еды и напитков',title:'WAVES Beach Lounge',subtitle:'Лёгкое меню, быстро открывается на телефонах.',search:'Поиск по меню...'}
};
const data=[
{icon:'☀️',cat:{ar:'إفطار',en:'Breakfast',ru:'Завтраки'},items:[
['اومليت توست + عصير فريش','Omelette toast + fresh juice','Омлет-тост + свежий сок','',200],['سلامون توست + عصير فريش','Salmon toast + fresh juice','Тост с лососем + свежий сок','',230],['بيف بيكون توست + عصير فريش','Beef bacon toast + fresh juice','Тост с говяжьим беконом + сок','',260],['باكيت بطاطس','French fries packet','Картофель фри','',50],['لوديد فرايز','Loaded fries','Картофель фри с топпингами','',150],['اونيون رينج باكيت','Onion rings packet','Луковые кольца','',150]]},
{icon:'🥞',cat:{ar:'كريب',en:'Crepes',ru:'Крепы'},items:[
['كريب ستربس','Chicken strips crepe','Креп с куриными стрипсами','',250],['كريب شاورما','Shawarma crepe','Креп с шаурмой','',250],['كريب كفته','Kofta crepe','Креп с кёфтой','',200],['كريب سوسيس','Sausage crepe','Креп с сосисками','',180],['كريب بطاطس','Potato crepe','Креп с картофелем','',150],['كريب نوتيلا','Nutella crepe','Креп с Нутеллой','',150],['كريب نوتيلا موز','Nutella banana crepe','Креп Нутелла-банан','',180],['كريب نوتيلا اوريو','Nutella Oreo crepe','Креп Нутелла-Орео','',180],['كريب لوتس','Lotus crepe','Креп Лотус','',180]]},
{icon:'🍔',cat:{ar:'برجر عالفحم',en:'Charcoal Burgers',ru:'Бургеры на углях'},items:[
['برجر كلاسيك / تشيكن برجر','Classic burger / Chicken burger','Классический / Куриный бургер','برجر، خس، خبز، باربكيو، صوص تيكساس',160],['برجر رانش بيف','Ranch beef burger','Говяжий бургер ранч','شيدر، خس، رانش، باربكيو، تيكساس',175],['رويال برجر','Royal burger','Роял бургер','شيدر، بصل مكرمل، خس، باربكيو، تيكساس',190],['برجر بيكون مشروم','Bacon mushroom burger','Бургер бекон-грибы','بيكون، مشروم، خس، باربكيو، تيكساس',210],['دبل ميكس','Double mix burger','Дабл микс бургер','2 برجر، موتزاريلا ستيكس، شيدر، خس',220],['حوواشي','Hawawshi','Хававши','',140],['حوواشي موتزاريلا شيدر','Hawawshi mozzarella & cheddar','Хававши с моцареллой и чеддером','',185]]},
{icon:'🍕',cat:{ar:'بيتزا',en:'Pizza',ru:'Пицца'},items:[
['مارجريتا','Margherita','Маргарита','',200],['تشيز لافر','Cheese lover','Любитель сыра','',260],['سجق','Sausage','С колбасками','',300],['بيبروني','Pepperoni','Пепперони','',300],['تشيكن رانش','Chicken ranch','Курица ранч','',300],['سوبر سوبريم','Super supreme','Супер суприм','',420],['ميكس لحوم','Meat mix','Микс мяса','',464]]},
{icon:'🥪',cat:{ar:'ساندويتشات',en:'Sandwiches',ru:'Сэндвичи'},items:[
['ساندويتش بطاطس','Potato sandwich','Сэндвич с картофелем','',65],['ساندويتش سوسيس','Sausage sandwich','Сэндвич с сосисками','',80],['ساندويتش كفته','Kofta sandwich','Сэндвич с кёфтой','',100],['ساندويتش ستربس','Strips sandwich','Сэндвич со стрипсами','',130],['ساندويتش جمبري','Shrimp sandwich','Сэндвич с креветками','',160]]},
{icon:'🍰',cat:{ar:'حلويات',en:'Desserts',ru:'Десерты'},items:[
['زلابية','Zalabia','Залабия','', '80 / 100 / 130'],['فروت سلاط','Fruit salad','Фруктовый салат','', '100 / 150 / 180'],['فشار','Popcorn','Попкорн','',60],['وافل ستيك','Waffle stick','Вафля на палочке','',80],['وافل كبير','Large waffle','Большая вафля','',150],['بان كيكس','Pancakes','Панкейки','',180],['فريسكا رول','Freska roll','Фреска ролл','',60],['مولتن كيك','Molten cake','Молтен кейк','',200],['شورت كيك','Short cake','Шорткейк','',100],['تراميسيو','Tiramisu','Тирамису','',120]]},
{icon:'☕',cat:{ar:'اسبريسو بار',en:'Espresso Bar',ru:'Эспрессо бар'},items:[
['V60','V60','V60','',90],['قهوة تركي','Turkish coffee','Турецкий кофе','',50],['اسبريسو','Espresso','Эспрессо','',65],['اسبريسو دبل','Espresso double','Двойной эспрессо','',85],['قهوة فرنسي','French coffee','Французский кофе','',75],['ماكياتو','Macchiato','Макиато','',90],['فلات وايت','Flat white','Флэт уайт','',95],['اسبريسو بونبون','Espresso bonbon','Эспрессо бонбон','',95],['لاتيه','Latte','Латте','',115],['كابتشينو','Cappuccino','Капучино','',115],['سولتد كراميل لاتيه','Salted caramel latte','Латте солёная карамель','',130],['سبانش لاتيه','Spanish latte','Испанский латте','',130],['هاني لاتيه','Honey latte','Медовый латте','',130]]},
{icon:'🌿',cat:{ar:'أعشاب',en:'Herbal',ru:'Травяные'},items:[
['شاي أحمر','Red tea','Чёрный чай','',40],['يانسون','Anise','Анис','',40],['نعناع','Mint','Мята','',40],['قرفة','Cinnamon','Корица','',40],['شاي أخضر','Green tea','Зелёный чай','',45]]},
{icon:'🧊',cat:{ar:'كولد كوفي',en:'Cold Coffee',ru:'Холодный кофе'},items:[
['V60','V60','V60','',150],['آيس أمريكانو','Iced americano','Айс американо','',120],['آيس لاتيه','Iced latte','Айс латте','',125],['آيس كابتشينو','Iced cappuccino','Айс капучино','',135],['كولد برو','Cold brew','Колд брю','',160],['آيس سبانش','Iced Spanish','Айс испанский латте','',150],['فرابيه / فرابتشينو','Frappe / Frappuccino','Фраппе / Фраппучино','',140]]},
{icon:'🍹',cat:{ar:'موكتيلز',en:'Mocktails',ru:'Моктейли'},items:[
['آيس تي كركديه','Hibiscus iced tea','Холодный чай с гибискусом','',90],['آيس تي خوخ','Peach iced tea','Холодный чай персик','',90],['موهيتو نعناع','Mint mojito','Мохито мята','',110],['باشن فريز','Passion frizz','Пэшн фриз','',110],['بلو فريز','Blue frizz','Блю фриз','',110],['شيري كولا','Cherry cola','Вишнёвая кола','',110],['بينا كولادا','Pina colada','Пина колада','',140],['واترليمون','Waterlemon','Арбуз-лимон','',140],['موهيتو ريد بول','Red Bull mojito','Мохито Ред Булл','',140]]},
{icon:'🍊',cat:{ar:'عصائر فريش',en:'Fresh Juices',ru:'Свежие соки'},items:[
['ليمون نعناع','Lemon mint','Лимон с мятой','',100],['رمان','Pomegranate','Гранат','',120],['برتقال','Orange','Апельсин','',120],['بطيخ','Watermelon','Арбуз','',110],['موز باللبن','Banana with milk','Банан с молоком','',110],['فراولة','Strawberry','Клубника','',110],['كيوي','Kiwi','Киви','',120],['جوافة','Guava','Гуава','',110],['مانجو','Mango','Манго','',130],['أفوكادو','Avocado','Авокадо','',160]]},
{icon:'🧋',cat:{ar:'ماتشا & بوبا',en:'Matcha & Boba',ru:'Матча и боба'},items:[
['براون شوغر ميلك تي','Brown sugar milk tea','Молочный чай с коричневым сахаром','',140],['ماتشا لاتيه','Matcha latte','Матча латте','',160],['آيس لاتيه بوبا','Iced latte boba','Айс латте боба','',160],['ستروبري ميلك بوبا','Strawberry milk boba','Клубничная молочная боба','',160],['مانجو بوبا','Mango boba','Манго боба','',180],['آيسد ماتشا','Iced matcha','Айс матча','',160],['كوكونات ماتشا','Coconut matcha','Кокосовая матча','',180],['ستروبري ماتشا','Strawberry matcha','Клубничная матча','',200],['سبانش لاتيه بوبا','Spanish latte boba','Испанский латте боба','',200],['ماتشا بوبا','Matcha boba','Матча боба','',220]]},
{icon:'🥤',cat:{ar:'سموزي',en:'Smoothies',ru:'Смузи'},items:[
['ليمون نعناع','Lemon mint','Лимон с мятой','',130],['بلو بيري','Blueberry','Черника','',140],['فراولة','Strawberry','Клубника','',140],['بطيخ','Watermelon','Арбуз','',140],['مانجو','Mango','Манго','',150]]},
{icon:'🍦',cat:{ar:'ميلك شيك',en:'Milkshakes',ru:'Милкшейки'},items:[
['فراولة','Strawberry','Клубника','',150],['مانجو','Mango','Манго','',150],['بلو بيري','Blueberry','Черника','',150],['بيستاشيو','Pistachio','Фисташка','',160],['أوريو','Oreo','Орео','',165],['لوتس','Lotus','Лотус','',165]]},
{icon:'💨',cat:{ar:'شيشة',en:'Shisha',ru:'Кальян'},items:[
['معسل','Maassal','Табак','',60],['فواكه','Fruits','Фрукты','بطيخ، توت أزرق، تفاحتين، عنب، فانيليا، ليمون نعناع',170]]},
{icon:'➕',cat:{ar:'إضافات',en:'Add-ons',ru:'Добавки'},items:[
['إضافة صوص','Extra sauce','Дополнительный соус','',20],['آيس كريم','Ice cream','Мороженое','',40],['فواكه','Fruits','Фрукты','',60],['فليفر سيرب','Flavor syrup','Сироп','فانيليا، بندق، كراميل',20],['بلانت ميلك','Plant milk','Растительное молоко','لوز، شوفان، جوز هند',30],['بوبا توبينج','Boba topping','Топпинг боба','',30],['اكسترا شوت','Extra shot','Доп. шот','',40]]}
];
let lang='ar',active='all';
const $=s=>document.querySelector(s);
const cats=$('#cats'), menu=$('#menu'), search=$('#search');
function dir(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr'}
function label(v){return v[lang==='ar'?0:lang==='en'?1:2]}
function renderCats(){cats.innerHTML=`<button class="${active==='all'?'active':''}" data-cat="all">${lang==='ar'?'الكل':lang==='en'?'All':'Все'}</button>`+data.map((s,i)=>`<button class="${active==i?'active':''}" data-cat="${i}">${s.icon} ${s.cat[lang]}</button>`).join('')}
function render(){dir();document.querySelectorAll('[data-i]').forEach(el=>el.textContent=t[lang][el.dataset.i]);search.placeholder=t[lang].search;renderCats();const q=search.value.trim().toLowerCase();menu.innerHTML='';data.forEach((s,i)=>{if(active!=='all'&&String(i)!==String(active))return;let items=s.items.filter(it=>(label(it)+' '+it[3]+' '+it[4]).toLowerCase().includes(q));if(!items.length)return;const card=document.createElement('article');card.className='section';card.innerHTML=`<h3>${s.icon} ${s.cat[lang]}</h3>`+items.map(it=>`<div class="item"><div><div class="name">${label(it)}</div>${it[3]?`<div class="desc">${it[3]}</div>`:''}</div><div class="price">${it[4]}</div></div>`).join('');menu.appendChild(card)})}
document.querySelectorAll('.langs button').forEach(b=>b.onclick=()=>{lang=b.dataset.lang;document.querySelectorAll('.langs button').forEach(x=>x.classList.toggle('active',x===b));render()});cats.onclick=e=>{if(e.target.tagName==='BUTTON'){active=e.target.dataset.cat;render()}};search.oninput=render;render();
